var PlayerInfo = 
{
    "Tools":
    {
        "Sword":         1,
        "Axe":           1,
        "Pickaxe":       1,
    },
    "Enchantments":
    {
        "Sharpness":     1,
        "Efficiency":    1,
        "Fortune":       1,
        "Protection":    1
    },
    "stats":
    {
        "health":        100,
        "Hunger":        100,
        "XP":            0,
        "Levels":        0
    },
    "Items":
    [
        {"Stone" : 0},
        {"Granite" : 0},
        {"Polished Granite" : 0},
        {"Diorite" : 0},
        {"Polished Diorite" : 0},
        {"Andesite" : 0},
        {"Polished Andesite" : 0},
        {"Grass" : 0},
        {"Dirt" : 0},
        {"Coarse Dirt" : 0},
        {"Podzol" : 0},
        {"Cobblestone" : 0},
        {"Oak Wood Plank" : 0},
        {"Spruce Wood Plank" : 0},
        {"Birch Wood Plank" : 0},
        {"Jungle Wood Plank" : 0},
        {"Acacia Wood Plank" : 0},
        {"Dark Oak Wood Plank" : 0},
        {"Oak Sapling" : 0},
        {"Spruce Sapling" : 0},
        {"Birch Sapling" : 0},
        {"Jungle Sapling" : 0},
        {"Acacia Sapling" : 0},
        {"Dark oak Sapling" : 0},
        {"Bedrock" : 0},
        {"Sand" : 0},
        {"Red Sand" : 0},
        {"Gravel" : 0},
        {"Gold Ore" : 0},
        {"Iron Ore" : 0},
        {"Coal Ore" : 0},
        {"Oak Wood" : 0},
        {"Spruce Wood" : 0},
        {"Birch Wood" : 0},
        {"Jungle Wood" : 0},
        {"Oak Leaves" : 0},
        {"Spruce Leaves" : 0},
        {"Birch Leaves" : 0},
        {"Jungle Leaves" : 0},
        {"Sponge" : 0},
        {"Wet Sponge" : 0},
        {"Glass" : 0},
        {"Lapis Lazuli Ore" : 0},
        {"Lapis Lazuli Block" : 0},
        {"Dispenser" : 0},
        {"Sandstone" : 0},
        {"Chiseled Sandstone" : 0},
        {"Smooth Sandstone" : 0},
        {"Note Block" : 0},
        {"Bed" : 0},
        {"Powered Rail" : 0},
        {"Detector Rail" : 0},
        {"Sticky Piston" : 0},
        {"Cobweb" : 0},
        {"Dead Shrub" : 0},
        {"Grass" : 0},
        {"Fern" : 0},
        {"Dead Bush" : 0},
        {"Piston" : 0},
        {"Dandelion" : 0},
        {"Poppy" : 0},
        {"Blue Orchid" : 0},
        {"Allium" : 0},
        {"Azure Blulet" : 0},
        {"Red Tulip": 0},
        {"Orange Tulip" : 0},
        {"White Tulip" : 0},
        {"Pink Tulip" : 0},
        {"Oxeye Daisy" : 0},
        {"Brown Mushroom" : 0},
        {"Red Mushroom" : 0},
        {"Gold Block" : 0},
        {"Iron Block" : 0},
        {"Stone Slab" : 0},
        {"Sandstone Slab" : 0},
        {"Wooden Slab" : 0},
        {"Cobblestone Slab" : 0},
        {"Brick Slab" : 0},
        {"Stone Brick Slab" : 0},
        {"Nether Brick Slab" : 0},
        {"Quartz Slab" : 0},
        {"Bricks" : 0},
        {"TNT" : 0},
        {"Bookshelf" : 0},
        {"Moss Stone" : 0},
        {"Obsidian" : 0},
        {"Torch" : 0},
        {"Oak Wood Stairs" : 0},
        {"Chest" : 0},
        {"Diamond Ore" : 0},
        {"Diamond Block" : 0},
        {"Crafting Table" : 0},
        {"Furnace" : 0},
        {"Sign" : 0},
        {"Oak Door" : 0},
        {"Ladder" : 0},
        {"Rail" : 0},
        {"Cobblestone Stairs" : 0},
        {"Lever" : 0},
        {"Stone Pressure Plate" : 0},
        {"Iron Door" : 0},
        {"Wooden Pressure Plate" : 0},
        {"Redstone Ore" : 0},
        {"Redstone Torch" : 0},
        {"Stone Button" : 0},
        {"Snow" : 0},
        {"Ice" : 0},
        {"Cactus" : 0},
        {"Clay" : 0},
        {"Sugar Canes" : 0},
        {"Jukebox" : 0},
        {"Oak Fence" : 0},
        {"Pumpkin" : 0},
        {"Netherrack" : 0},
        {"Soul Sand" : 0},
        {"Glowstone" : 0},
        {"Jack o'Lantern" : 0},
        {"Cake" : 0},
        {"Redstone Repeater" : 0},
        {"Wooden Trapdoor" : 0},
        {"Stone Bricks" : 0},
        {"Mossy Stone Bricks" : 0},
        {"Cracked Stone Bricks" : 0},
        {"Chiseled Stone Bricks" : 0},
        {"Brown Mushroom Block" : 0},
        {"Red Mushroom Block" : 0},
        {"Iron Bars" : 0},
        {"Glass Pane" : 0},
        {"Melon" : 0},
        {"Vines" : 0},
        {"Oak Fence Gate" : 0},
        {"Brick Stairs" : 0},
        {"Stone Brick Stairs" : 0},
        {"Mycelium" : 0},
        {"Lily Pad" : 0},
        {"Nether Brick" : 0},
        {"Nether Brick Fence" : 0},
        {"Nether Brick Stairs" : 0},
        {"Nether Wart" : 0},
        {"Enchantment Table" : 0},
        {"Brewing Stand" : 0},
        {"Cauldron" : 0},
        {"End Portal Frame" : 0},
        {"End Stone" : 0},
        {"Dragon Egg" : 0},
        {"Redstone Lamp" : 0},
        {"Oak Wood Slab" : 0},
        {"Spruce Wood Slab" : 0},
        {"Birch Wood Slab" : 0},
        {"Jungle Wood Slab" : 0},
        {"Acacia Wood Slab" : 0},
        {"Dark Oak Wood Slab" : 0},
        {"Cocoa" : 0},
        {"Sandstone Stairs" : 0},
        {"Emerald Ore" : 0},
        {"Ender Chest" : 0},
        {"Tripwire Hook" : 0},
        {"Emerald Block" : 0},
        {"Spruce Wood Stairs" : 0},
        {"Birch Wood Stairs" : 0},
        {"Jungle Wood Stairs" : 0},
        {"Beacon" : 0},
        {"Cobblestone Wall" : 0},
        {"Mossy Cobblestone Wall" : 0},
        {"Flower Pot" : 0},
        {"Carrots" : 0},
        {"Potatoes" : 0},
        {"Wooden Button" : 0},
        {"Mob Head" : 0},
        {"Anvil" : 0},
        {"Trapped Chest" : 0},
        {"Golden Pressure Plate" : 0},
        {"Iron Pressure Plate" : 0},
        {"Comparator" : 0},
        {"Daylight Sensor" : 0},
        {"Redstone Block" : 0},
        {"Nether Quartz Ore" : 0},
        {"Hopper" : 0},
        {"Quartz Block" : 0},
        {"Chiseled Quartz Block" : 0},
        {"Pillar Quartz Block" : 0},
        {"Quartz Stairs" : 0},
        {"Activator Rail" : 0},
        {"Dropper" : 0},
        {"Acacia Leaves" : 0},
        {"Dark Oak Leaves" : 0},
        {"Acacia Wood" : 0},
        {"Dark Oak Wood" : 0},
        {"Acacia Wood Stairs" : 0},
        {"Dark Oak Wood Stairs" : 0},
        {"Slime Block" : 0},
        {"Iron Trapdoor" : 0},
        {"Prismarine" : 0},
        {"Prismarine Bricks" : 0},
        {"Dark Prismarine" : 0},
        {"Sea Lantern" : 0},
        {"Hay Bale" : 0},
        {"Hardened Clay" : 0},
        {"Block of Coal" : 0},
        {"Packed Ice" : 0},
        {"Sunflower" : 0},
        {"Lilac" : 0},
        {"Banner" : 0},
        {"Red Sandstone" : 0},
        {"Chiseled Red Sandstone" : 0},
        {"Smooth Red Sandstone" : 0},
        {"Red Sandstone Stairs" : 0},
        {"Double Red Sandstone Slab" : 0},
        {"Red Sandstone Slab" : 0},
        {"Spruce Fence Gate" : 0},
        {"Birch Fence Gate" : 0},
        {"Jungle Fence Gate" : 0},
        {"Dark Oak Fence Gate" : 0},
        {"Acacia Fence Gate" : 0},
        {"Spruce Fence" : 0},
        {"Birch Fence" : 0},
        {"Jungle Fence" : 0},
        {"Dark Oak Fence" : 0},
        {"Acacia Fence" : 0},
        {"Spruce Door" : 0},
        {"Birch Door" : 0},
        {"Jungle Door" : 0},
        {"Acacia Door" : 0},
        {"Dark Oak Door" : 0},
        {"End Rod" : 0},
        {"Chorus Plant" : 0},
        {"Chorus Flower" : 0},
        {"Purpur Block" : 0},
        {"Purpur Pillar" : 0},
        {"Purpur Stairs" : 0},
        {"Purpur Double Slab" : 0},
        {"Purpur Slab" : 0},
        {"End Stone Bricks" : 0},
        {"Frosted Ice" : 0},
        {"Magma Block" : 0},
        {"Nether Wart Block" : 0},
        {"Red Nether Brick" : 0},
        {"Bone Block" : 0},
        {"Observer" : 0},
        {"Shulker Box" : 0},
        {"Terracotta" : 0},
        {"Concrete" : 0},
        {"Concrete Powder" : 0},
        {"Iron Shovel" : 0},
        {"Iron Pickaxe" : 0},
        {"Iron Axe" : 0},
        {"Flint and Steel" : 0},
        {"Apple" : 0},
        {"Bow" : 0},
        {"Arrow" : 0},
        {"Coal" : 0},
        {"Charcoal" : 0},
        {"Diamond" : 0},
        {"Iron Ingot" : 0},
        {"Gold Ingot" : 0},
        {"Iron Sword" : 0},
        {"Wooden Sword" : 0},
        {"Wooden Shovel" : 0},
        {"Wooden Pickaxe" : 0},
        {"Wooden Axe" : 0},
        {"Stone Sword" : 0},
        {"Stone Shovel" : 0},
        {"Stone Pickaxe" : 0},
        {"Stone Axe" : 0},
        {"Diamond Sword" : 0},
        {"Diamond Shovel" : 0},
        {"Diamond Pickaxe" : 0},
        {"Diamond Axe" : 0},
        {"Stick" : 0},
        {"Bowl" : 0},
        {"Golden Sword" : 0},
        {"Golden Shovel" : 0},
        {"Golden Pickaxe" : 0},
        {"Golden Axe" : 0},
        {"String" : 0},
        {"Feather" : 0},
        {"Gunpowder" : 0},
        {"Wooden Hoe" : 0},
        {"Stone Hoe" : 0},
        {"Iron Hoe" : 0},
        {"Diamond Hoe" : 0},
        {"Golden Hoe" : 0},
        {"Seeds" : 0},
        {"Wheat" : 0},
        {"Bread" : 0},
        {"Leather Helmet" : 0},
        {"Leather Tunic" : 0},
        {"Leather Pants" : 0},
        {"Leather Boots" : 0},
        {"Chainmail Helmet" : 0},
        {"Chainmail Tunic" : 0},
        {"Chainmail Pants" : 0},
        {"Chainmail Boots" : 0},
        {"Iron Helmet" : 0},
        {"Iron Tunic" : 0},
        {"Iron Pants" : 0},
        {"Iron Boots" : 0},
        {"Diamond Helmet" : 0},
        {"Diamond Tunic" : 0},
        {"Diamond Pants" : 0},
        {"Diamond Boots" : 0},
        {"Gold Helmet" : 0},
        {"Gold Tunic" : 0},
        {"Gold Pants" : 0},
        {"Gold Boots" : 0},
        {"Flint" : 0},
        {"Raw Porkchop" : 0},
        {"Cooked Porkchop" : 0},
        {"Painting" : 0},
        {"Golden Apple" : 0},
        {"Enchanted Golden Apple" : 0},
        {"Oak Door" : 0},
        {"Bucket" : 0},
        {"Water Bucket" : 0},
        {"lava Bucket" : 0},
        {"Minecart" : 0},
        {"Saddle" : 0},
        {"Iron Door" : 0},
        {"Redstone" : 0},
        {"Snowball" : 0},
        {"Oak Boat" : 0},
        {"Leather" : 0},
        {"Milk Bucket" : 0},
        {"Brick" : 0},
        {"Clay" : 0},
        {"Sugar Canes" : 0},
        {"Paper" : 0},
        {"Book" : 0},
        {"Slimeball" : 0},
        {"Minecart with Chest" : 0},
        {"Minecart with Furnace" : 0},
        {"Egg" : 0},
        {"Compass" : 0},
        {"Fishing Rod" : 0},
        {"Clock" : 0},
        {"Glowstone Dust" : 0},
        {"Raw Fish" : 0},
        {"Raw Salmon" : 0},
        {"Clownfish" : 0},
        {"Pufferfish" : 0},
        {"Cooked Fish" : 0},
        {"Cooked Salmon" : 0},
        {"Bone Meal" : 0},
        {"Bone" : 0},
        {"Sugar" : 0},
        {"Cake" : 0},
        {"Bed" : 0},
        {"Cookie" : 0},
        {"Map" : 0},
        {"Shears" : 0},
        {"Melon" : 0},
        {"Raw Beef" : 0},
        {"Raw Chicken" : 0},
        {"Cooked Clicken" : 0},
        {"Rotten Flesh" : 0},
        {"Ender Pearl" : 0},
        {"Blaze Rod" : 0},
        {"Ghast Tear" : 0},
        {"Gold Nugget" : 0},
        {"Nether Wart" : 0},
        {"Glass Bottle" : 0},
        {"Spider Eye" : 0},
        {"Brewing Stand" : 0},
        {"Cauldron" : 0},
        {"Eye of Ender" : 0},
        {"Glisterint Melon" : 0},
        {"Bottle o' Enchanting" : 0},
        {"Fire Charge" : 0},
        {"Emerald" : 0},
        {"Carrot" : 0},
        {"Potato" : 0},
        {"Baked Potato" : 0},
        {"Golden Carrot" : 0},
        {"Nether Star" : 0},
        {"Firework Rocket" : 0},
        {"Pumpkin Pie" : 0},
        {"Firework Rocket" : 0},
        {"Nether Brick" : 0},
        {"Nether Quartz" : 0},
        {"Minecart with TNT" : 0},
        {"Minecart with Hopper" : 0},
        {"Prismarine Shard" : 0},
        {"Prismarine Crystals" : 0},
        {"Raw Rabbit" : 0},
        {"Cooked Rabbit" : 0},
        {"Rabbit Stew" : 0},
        {"Rabbit's Foot" : 0},
        {"Rabbit Hide" : 0},
        {"Armour Stand" : 0},
        {"Lead" : 0},
        {"Name Tag" : 0},
        {"Minecart with Command Block" : 0},
        {"Raw Mutton" : 0},
        {"Cooked Mutton" : 0},
        {"Banner" : 0},
        {"End Crystal" : 0},
        {"Chorus Fruit" : 0},
        {"Popped Chorus Fruit" : 0},
        {"Beetroot" : 0},
        {"Beetroot Soup" : 0},
        {"Dragon's Breath" : 0},
        {"Spectral Arrow" : 0},
        {"Shield" : 0},
        {"Elytra" : 0},
        {"Totem of Undying" : 0},
        {"Shulker Shell" : 0},
        {"Iron Nugget" : 0}
    ]
}

var useditems = 
[
    "Oak Logs",
    "Oak Planks"
]